# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  showIcons: true
  nerdFontsVersion: "3" # Use "2" if you have an older font version installed
  theme:
    lightTheme: false
    activeBorderColor:
      - "#7aa2f7"
      - bold
    inactiveBorderColor:
      - "#565f89"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#292e42"
    cherryPickedCommitBgColor:
      - "#414868"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
os:
  editPreset: 'nvim-remote'
