set -g prefix2 C-a
bind-key C-a send-prefix -2

# Clear all status bar bell alerts in current session. Shift+x.
bind X kill-session -C

set -g mouse on
set -g mode-keys vi
set -g status-keys vi

# Enable true colors
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:Tc"

set -g set-clipboard on

# Start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Automatically renumber windows when one is closed
set-option -g renumber-windows on

# Enable focus events so Neovim can detect when you switch panes
set -g focus-events on

# Fix claude code tmux issues
# see https://code.claude.com/docs/en/terminal-config#configure-tmux
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# persist sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-dir '~/.tmux/resurrect'
# resurrect these processeses
set -g @resurrect-processes 'lynx'
# for vim
set -g @resurrect-strategy-vim 'session'
# for neovim
set -g @resurrect-strategy-nvim 'session'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_theme default    # storm | day | default to 'night'
set -g @tokyo-night-tmux_transparent 1  # 1 or 0
set -g @tokyo-night-tmux_window_id_style none # defaults to digital clock not visible in termux and wsl. So I disabled it.
setw -g window-status-bell-style "fg=#f7768e bg=#1a1b26"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

